### PR TITLE
fix: non-streaming responses to store signatures

### LINKED ISSUE #211: Signatures are not stored when calling `responses` without stream
After calling `POST /responses` API with `stream: false`, we can not get any signatures from `GET /signature/{response_id}` API, it's because signatures are not stored

### PR DESCRIPTION
**Pull request by danielwpz**
Fixes #211

### CODE REVIEW

**Review by PierreLeGuen — APPROVED** [review]

File: crates/api/src/routes/responses.rs [hunk 1]
```diff
@@ -472,6 +472,27 @@ pub async fn create_response(
                     "Created response {} for key {}",
                     response.id, api_key.api_key.created_by_user_id.0
                 );
+
+                // Store signature for non-streaming response
+                let response_id = response.id.clone();
+                let response_json = serde_json::to_string(&response).unwrap_or_default();
```
Comment (PierreLeGuen) [inline crates/api/src/routes/responses.rs]: Let's return this json to the users.

**Review by PierreLeGuen — CHANGES_REQUESTED** [review]
